# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/orange/Expression_demo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/orange/Expression_demo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/orange/Expression_demo/CMakeFiles /home/orange/Expression_demo/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/orange/Expression_demo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fer_predict

# Build rule for target.
fer_predict: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fer_predict
.PHONY : fer_predict

# fast build rule for target.
fer_predict/fast:
	$(MAKE) -f CMakeFiles/fer_predict.dir/build.make CMakeFiles/fer_predict.dir/build
.PHONY : fer_predict/fast

#=============================================================================
# Target rules for targets named fer_train

# Build rule for target.
fer_train: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fer_train
.PHONY : fer_train

# fast build rule for target.
fer_train/fast:
	$(MAKE) -f CMakeFiles/fer_train.dir/build.make CMakeFiles/fer_train.dir/build
.PHONY : fer_train/fast

#=============================================================================
# Target rules for targets named fer_train_CK

# Build rule for target.
fer_train_CK: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fer_train_CK
.PHONY : fer_train_CK

# fast build rule for target.
fer_train_CK/fast:
	$(MAKE) -f CMakeFiles/fer_train_CK.dir/build.make CMakeFiles/fer_train_CK.dir/build
.PHONY : fer_train_CK/fast

#=============================================================================
# Target rules for targets named fer_train_jaffe

# Build rule for target.
fer_train_jaffe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fer_train_jaffe
.PHONY : fer_train_jaffe

# fast build rule for target.
fer_train_jaffe/fast:
	$(MAKE) -f CMakeFiles/fer_train_jaffe.dir/build.make CMakeFiles/fer_train_jaffe.dir/build
.PHONY : fer_train_jaffe/fast

#=============================================================================
# Target rules for targets named gather

# Build rule for target.
gather: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gather
.PHONY : gather

# fast build rule for target.
gather/fast:
	$(MAKE) -f CMakeFiles/gather.dir/build.make CMakeFiles/gather.dir/build
.PHONY : gather/fast

fer.o: fer.cpp.o
.PHONY : fer.o

# target to build an object file
fer.cpp.o:
	$(MAKE) -f CMakeFiles/fer_predict.dir/build.make CMakeFiles/fer_predict.dir/fer.cpp.o
	$(MAKE) -f CMakeFiles/fer_train.dir/build.make CMakeFiles/fer_train.dir/fer.cpp.o
	$(MAKE) -f CMakeFiles/fer_train_CK.dir/build.make CMakeFiles/fer_train_CK.dir/fer.cpp.o
	$(MAKE) -f CMakeFiles/fer_train_jaffe.dir/build.make CMakeFiles/fer_train_jaffe.dir/fer.cpp.o
	$(MAKE) -f CMakeFiles/gather.dir/build.make CMakeFiles/gather.dir/fer.cpp.o
.PHONY : fer.cpp.o

fer.i: fer.cpp.i
.PHONY : fer.i

# target to preprocess a source file
fer.cpp.i:
	$(MAKE) -f CMakeFiles/fer_predict.dir/build.make CMakeFiles/fer_predict.dir/fer.cpp.i
	$(MAKE) -f CMakeFiles/fer_train.dir/build.make CMakeFiles/fer_train.dir/fer.cpp.i
	$(MAKE) -f CMakeFiles/fer_train_CK.dir/build.make CMakeFiles/fer_train_CK.dir/fer.cpp.i
	$(MAKE) -f CMakeFiles/fer_train_jaffe.dir/build.make CMakeFiles/fer_train_jaffe.dir/fer.cpp.i
	$(MAKE) -f CMakeFiles/gather.dir/build.make CMakeFiles/gather.dir/fer.cpp.i
.PHONY : fer.cpp.i

fer.s: fer.cpp.s
.PHONY : fer.s

# target to generate assembly for a file
fer.cpp.s:
	$(MAKE) -f CMakeFiles/fer_predict.dir/build.make CMakeFiles/fer_predict.dir/fer.cpp.s
	$(MAKE) -f CMakeFiles/fer_train.dir/build.make CMakeFiles/fer_train.dir/fer.cpp.s
	$(MAKE) -f CMakeFiles/fer_train_CK.dir/build.make CMakeFiles/fer_train_CK.dir/fer.cpp.s
	$(MAKE) -f CMakeFiles/fer_train_jaffe.dir/build.make CMakeFiles/fer_train_jaffe.dir/fer.cpp.s
	$(MAKE) -f CMakeFiles/gather.dir/build.make CMakeFiles/gather.dir/fer.cpp.s
.PHONY : fer.cpp.s

fer_predict.o: fer_predict.cpp.o
.PHONY : fer_predict.o

# target to build an object file
fer_predict.cpp.o:
	$(MAKE) -f CMakeFiles/fer_predict.dir/build.make CMakeFiles/fer_predict.dir/fer_predict.cpp.o
.PHONY : fer_predict.cpp.o

fer_predict.i: fer_predict.cpp.i
.PHONY : fer_predict.i

# target to preprocess a source file
fer_predict.cpp.i:
	$(MAKE) -f CMakeFiles/fer_predict.dir/build.make CMakeFiles/fer_predict.dir/fer_predict.cpp.i
.PHONY : fer_predict.cpp.i

fer_predict.s: fer_predict.cpp.s
.PHONY : fer_predict.s

# target to generate assembly for a file
fer_predict.cpp.s:
	$(MAKE) -f CMakeFiles/fer_predict.dir/build.make CMakeFiles/fer_predict.dir/fer_predict.cpp.s
.PHONY : fer_predict.cpp.s

fer_train.o: fer_train.cpp.o
.PHONY : fer_train.o

# target to build an object file
fer_train.cpp.o:
	$(MAKE) -f CMakeFiles/fer_train.dir/build.make CMakeFiles/fer_train.dir/fer_train.cpp.o
.PHONY : fer_train.cpp.o

fer_train.i: fer_train.cpp.i
.PHONY : fer_train.i

# target to preprocess a source file
fer_train.cpp.i:
	$(MAKE) -f CMakeFiles/fer_train.dir/build.make CMakeFiles/fer_train.dir/fer_train.cpp.i
.PHONY : fer_train.cpp.i

fer_train.s: fer_train.cpp.s
.PHONY : fer_train.s

# target to generate assembly for a file
fer_train.cpp.s:
	$(MAKE) -f CMakeFiles/fer_train.dir/build.make CMakeFiles/fer_train.dir/fer_train.cpp.s
.PHONY : fer_train.cpp.s

gather.o: gather.cpp.o
.PHONY : gather.o

# target to build an object file
gather.cpp.o:
	$(MAKE) -f CMakeFiles/gather.dir/build.make CMakeFiles/gather.dir/gather.cpp.o
.PHONY : gather.cpp.o

gather.i: gather.cpp.i
.PHONY : gather.i

# target to preprocess a source file
gather.cpp.i:
	$(MAKE) -f CMakeFiles/gather.dir/build.make CMakeFiles/gather.dir/gather.cpp.i
.PHONY : gather.cpp.i

gather.s: gather.cpp.s
.PHONY : gather.s

# target to generate assembly for a file
gather.cpp.s:
	$(MAKE) -f CMakeFiles/gather.dir/build.make CMakeFiles/gather.dir/gather.cpp.s
.PHONY : gather.cpp.s

train_CK.o: train_CK.cpp.o
.PHONY : train_CK.o

# target to build an object file
train_CK.cpp.o:
	$(MAKE) -f CMakeFiles/fer_train_CK.dir/build.make CMakeFiles/fer_train_CK.dir/train_CK.cpp.o
.PHONY : train_CK.cpp.o

train_CK.i: train_CK.cpp.i
.PHONY : train_CK.i

# target to preprocess a source file
train_CK.cpp.i:
	$(MAKE) -f CMakeFiles/fer_train_CK.dir/build.make CMakeFiles/fer_train_CK.dir/train_CK.cpp.i
.PHONY : train_CK.cpp.i

train_CK.s: train_CK.cpp.s
.PHONY : train_CK.s

# target to generate assembly for a file
train_CK.cpp.s:
	$(MAKE) -f CMakeFiles/fer_train_CK.dir/build.make CMakeFiles/fer_train_CK.dir/train_CK.cpp.s
.PHONY : train_CK.cpp.s

train_jaffe.o: train_jaffe.cpp.o
.PHONY : train_jaffe.o

# target to build an object file
train_jaffe.cpp.o:
	$(MAKE) -f CMakeFiles/fer_train_jaffe.dir/build.make CMakeFiles/fer_train_jaffe.dir/train_jaffe.cpp.o
.PHONY : train_jaffe.cpp.o

train_jaffe.i: train_jaffe.cpp.i
.PHONY : train_jaffe.i

# target to preprocess a source file
train_jaffe.cpp.i:
	$(MAKE) -f CMakeFiles/fer_train_jaffe.dir/build.make CMakeFiles/fer_train_jaffe.dir/train_jaffe.cpp.i
.PHONY : train_jaffe.cpp.i

train_jaffe.s: train_jaffe.cpp.s
.PHONY : train_jaffe.s

# target to generate assembly for a file
train_jaffe.cpp.s:
	$(MAKE) -f CMakeFiles/fer_train_jaffe.dir/build.make CMakeFiles/fer_train_jaffe.dir/train_jaffe.cpp.s
.PHONY : train_jaffe.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... fer_predict"
	@echo "... fer_train"
	@echo "... fer_train_CK"
	@echo "... fer_train_jaffe"
	@echo "... gather"
	@echo "... rebuild_cache"
	@echo "... fer.o"
	@echo "... fer.i"
	@echo "... fer.s"
	@echo "... fer_predict.o"
	@echo "... fer_predict.i"
	@echo "... fer_predict.s"
	@echo "... fer_train.o"
	@echo "... fer_train.i"
	@echo "... fer_train.s"
	@echo "... gather.o"
	@echo "... gather.i"
	@echo "... gather.s"
	@echo "... train_CK.o"
	@echo "... train_CK.i"
	@echo "... train_CK.s"
	@echo "... train_jaffe.o"
	@echo "... train_jaffe.i"
	@echo "... train_jaffe.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

